# Generated by Django 5.1.1 on 2025-03-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_rename_githun_link_userprojects_github_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprojects",
            name="project_picture",
            field=models.ImageField(upload_to="media/image/ProjectsImages"),
        ),
    ]
