# Generated by Django 5.1.1 on 2025-03-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0005_alter_userprojects_project_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprojects",
            name="project_picture",
            field=models.ImageField(upload_to="image/ProjectsImages"),
        ),
    ]
