# Generated by Django 5.1.1 on 2025-03-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0006_alter_userprojects_project_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                ("date_update", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
